app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /api
    defaults:
        _format: json


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
   path: /api/login_check
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
# app:
#     resource: "@UserBundle/Controller/"
#     type:     annotation
#     prefix:   /users
#     defaults:
#         _format: json